### PR TITLE
Pull request to the master branch

### PR DESCRIPTION
**Pull request by moudio**
We finished building the project and are making a pull request to the master branch.

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
Hi @MouhaDiouf @emmanuelkamala ,

Good job. Your code is error free well done guys.
Here is the checklist for your project.
- To consider the project 'complete' it must satisfy the following points:
## Main Content
- [ ] Any sections that include text (paragraphs) should be wrapped with a `<section>` tag and include an `<aside>` tag for Editor's picks and a Sign-Up button.
## Bottom
- [ ] It should have a 'Read comments' button and social media icons (fontawsome is recommended for the icons)

Kindly add the following screenshot to the project;
image


image


After fixing the unchecked issue and adding of the extra pieces please send another request to re-review this project.

Thanks 🙏

**Comment by moudio** [comment]
We added the sections and the aside to our HTML file. Now we don't see the signup button in our laptops.

**Comment by Torres-ssf** [comment]
Hi @MouhaDiouf  @emmanuelkamala.
You guys are doing a good job in this project and should be proud of it. But before I give a 👍, you need to add just two things. You guys forget to add the 'Second Editor's Picks(There are two on this page) and Sign Up for Science Times button'. They both are in the middle of the page, living aside the main article. My friend who did the last review posted images from these 2 features, that you need to add. Please, kindly fix this and submit to code review again.

**Review by bellom — CHANGES_REQUESTED** [review]
Hi @MouhaDiouf @emmanuelkamala,
You guys have really done a very good job, is just that i guess you didn't preview your live version before submitting another code review.
Just a minor thing to do, the article you added wasn't in the right position, screenshot from your live version below; 

image

**I checked you guys online but offline, had it been you're online could have just tell you to correct and give you guys** :+1:
**Kindly correct the above screenshot from your web page and re-submit another code review.**

_Can't wait to give you guys thumbs-up_ :smile:

**Comment by Torres-ssf** [comment]
### Nice work  👍 
You can merge to master now. Don't forget to submit the form

**Pull request merged**
